name: CI Android

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11
      - name: Build with Gradle
        run: ./gradlew assembleDebug
      - name: Install Android SDK
        uses: malinskiy/action-android/install-sdk@release/0.1.2
      - name: Android Emulator test
        uses: malinskiy/action-android/emulator-run-cmd@release/0.1.2
        with:
          cmd: ./gradlew cAT --continue
          api: 28
          tag: default
          abi: x86
          cmdOptions: -noaudio -no-boot-anim -no-window
      - uses: actions/upload-artifact@v2.2.4
        if: ${{ always() }}
        with:
          name: Espresso-test-mqtt-report
          path: ./**/build/reports/androidTests/connected
      - name: Archive screenshots
        uses: actions/upload-artifact@v2.2.4
        if: ${{ always() }}
        with:
          name: PGL-Screenshots
          path: screenshots/adb
  Check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Install Android SDK
        uses: malinskiy/action-android/install-sdk@release/0.1.2
      - name: Code checks
        run: ./gradlew check
      - name: Archive Lint report
        uses: actions/upload-artifact@v2.2.4
        if: ${{ always() }}
        with:
          name: PGL-Lint-report
          path: ./**/build/reports/lint-results.html
